# Generated by Django 5.1.6 on 2025-06-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_total_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='total_tickets',
        ),
    ]
