# Generated by Django 5.1.6 on 2025-07-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('sports', 'Sports Events'), ('entertainment', 'Entertainment Events'), ('civic', 'Civic and Political Events'), ('educational', 'Educational and Institutional Events'), ('corporate', 'Corporate and Business Events'), ('religious', 'Religious and Spiritual Events'), ('recreational', 'Recreational and Community Events'), ('esports', 'E-sports and Virtual Events')], default='sports', max_length=32),
        ),
    ]
