# Generated by Django 5.1.6 on 2025-07-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='league',
            field=models.CharField(blank=True, choices=[('premier_league', 'Premier League'), ('national_league', 'National League'), ('champions_league', 'Champions League')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sport_type',
            field=models.CharField(blank=True, choices=[('football', 'Football'), ('basketball', 'Basketball'), ('athletics', 'Athletics'), ('rugby', 'Rugby'), ('tennis', 'Tennis')], max_length=32, null=True),
        ),
    ]
