# Generated by Django 5.1.6 on 2025-08-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_league_event_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('ol_kalou', 'Ol Kalou Stadium'), ('kararani', 'Kararani Stadium (Ndunyu Njeru)')], default='ol_kalou', max_length=32),
        ),
    ]
