# Generated by Django 5.1.6 on 2025-06-23 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_total_tickets'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VVIP', 'VVIP'), ('VIP', 'VIP'), ('Executive', 'Executive / Corporate Box'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze / Standard'), ('Economy', 'Economy / Regular'), ('Early Bird', 'Early Bird'), ('Group', 'Group / Family Pass'), ('Student', 'Student / Youth / Child Ticket'), ('Season', 'Season Pass'), ('All Access', 'All-Access Pass'), ('Press', 'Press / Media Pass'), ('Backstage', 'Backstage / Meet & Greet Pass'), ('Disabled', 'Disabled / Accessibility Ticket')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_available', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
        ),
    ]
