# Generated by Django 5.1.6 on 2025-06-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_tickettype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tickettype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.tickettype'),
        ),
    ]
