# Generated by Django 5.1.6 on 2025-07-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_tickettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_qrcodes/'),
        ),
    ]
