# Generated by Django 5.1.6 on 2025-08-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='seats',
            field=models.CharField(blank=True, help_text='Comma-separated seat numbers, e.g. A1,A2,A3', max_length=500),
        ),
    ]
